// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkTrackBio.API.Data;

#nullable disable

namespace WorkTrackBio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.AbsenceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AbsenceDate")
                        .HasColumnType("date");

                    b.Property<string>("AbsenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RegisteredById")
                        .HasColumnType("int");

                    b.Property<int?>("VacationRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("VacationRequestId");

                    b.HasIndex("EmployeeInfoId", "AbsenceDate");

                    b.ToTable("AbsenceRecords");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeInfoId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Assistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CheckInDateOnly")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RegisterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("EmployeeId", "CheckIn");

                    b.ToTable("Assistances");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ChristmasBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("SuggestedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalEarned")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedById");

                    b.HasIndex("EmployeeInfoId", "Year")
                        .IsUnique();

                    b.ToTable("ChristmasBonuses");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ChristmasBonusDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChristmasBonusId")
                        .HasColumnType("int");

                    b.Property<decimal>("EarnedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("PayrollEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChristmasBonusId");

                    b.HasIndex("PayrollEntryId");

                    b.ToTable("ChristmasBonusDetails");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Disability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CCSSPaidDays")
                        .HasColumnType("int");

                    b.Property<string>("CSSDocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisabilityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<int>("EmployerPaidDays")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeInfoId");

                    b.ToTable("Disabilities");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeDeduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeductionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeInfoId");

                    b.ToTable("EmployeeDeductions");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FileRegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeInfoId");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<bool>("CanClaimExpenses")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DocumentExpire")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpouseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("StateId");

                    b.ToTable("EmployeeInfos");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Liquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalChristmasBonus")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalNoticePay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalSeverancePay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalVacationPay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SuggestedChristmasBonus")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SuggestedNoticePay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SuggestedSeverancePay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SuggestedTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SuggestedVacationPay")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedById");

                    b.HasIndex("EmployeeInfoId");

                    b.ToTable("Liquidations");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollDeduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeDeductionId")
                        .HasColumnType("int");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeDeductionId");

                    b.HasIndex("PayrollId");

                    b.ToTable("PayrollDeductions");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("OvertimeAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("OvertimeHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PayrollRunId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RegularHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeInfoId");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("PayrollEntries");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PayFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PaymentDate");

                    b.ToTable("PayrollRuns");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ProjectMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MadeById")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaintenanceCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MadeById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectMaintenances");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ProjectWarranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProject")
                        .HasColumnType("int");

                    b.Property<int>("MadeById")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WarrantyCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("WarrantyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarrantyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.HasIndex("MadeById");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectWarranties");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.SystemAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.TravelExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("EmployeeInfoId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StateId");

                    b.ToTable("TravelExpenses");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("EmployeeInfoId", "StartDate");

                    b.ToTable("VacationRequests");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.AbsenceRecord", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("AbsenceRecords")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkTrackBio.API.Data.Models.VacationRequest", "VacationRequest")
                        .WithMany()
                        .HasForeignKey("VacationRequestId");

                    b.Navigation("EmployeeInfo");

                    b.Navigation("RegisteredBy");

                    b.Navigation("VacationRequest");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.AppUser", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithOne("AppUser")
                        .HasForeignKey("WorkTrackBio.API.Data.Models.AppUser", "EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.Role", "Role")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInfo");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Assistance", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "Employee")
                        .WithMany("Assistances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.Project", "Project")
                        .WithMany("Assistances")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ChristmasBonus", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("ChristmasBonuses")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedBy");

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ChristmasBonusDetail", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.ChristmasBonus", "ChristmasBonus")
                        .WithMany("Details")
                        .HasForeignKey("ChristmasBonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.PayrollEntry", "PayrollEntry")
                        .WithMany()
                        .HasForeignKey("PayrollEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChristmasBonus");

                    b.Navigation("PayrollEntry");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Client", b =>
                {
                    b.OwnsOne("WorkTrackBio.API.Data.Models.ExonerationData", "Exoneration", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime?>("IssueDate")
                                .HasColumnType("datetime2");

                            b1.Property<decimal>("Percentage")
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Exoneration")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Disability", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("Disabilities")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeDeduction", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("EmployeeDeductions")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeDocument", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("EmployeeDocuments")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeInfo", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.Department", "Department")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.DocumentType", "DocumentType")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.State", "State")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WorkTrackBio.API.Data.Models.ExitData", "ExitInformation", b1 =>
                        {
                            b1.Property<int>("EmployeeInfoId")
                                .HasColumnType("int");

                            b1.Property<DateOnly?>("ExitDate")
                                .HasColumnType("date");

                            b1.Property<string>("ExitReason")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<bool>("IsRehire")
                                .HasColumnType("bit");

                            b1.Property<DateOnly?>("LiquidationDate")
                                .HasColumnType("date");

                            b1.Property<DateOnly?>("RehireDate")
                                .HasColumnType("date");

                            b1.HasKey("EmployeeInfoId");

                            b1.ToTable("EmployeeInfos");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeInfoId");
                        });

                    b.OwnsOne("WorkTrackBio.API.Data.Models.SalaryData", "Salary", b1 =>
                        {
                            b1.Property<int>("EmployeeInfoId")
                                .HasColumnType("int");

                            b1.Property<int>("AvailableVacationDays")
                                .HasColumnType("int");

                            b1.Property<decimal?>("CostPerHour")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal?>("FixedSalary")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<string>("PaymentFrequency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("UsedVacationDays")
                                .HasColumnType("int");

                            b1.HasKey("EmployeeInfoId");

                            b1.ToTable("EmployeeInfos");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeInfoId");
                        });

                    b.Navigation("Department");

                    b.Navigation("DocumentType");

                    b.Navigation("ExitInformation")
                        .IsRequired();

                    b.Navigation("Salary")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Liquidation", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("Liquidations")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedBy");

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollDeduction", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeDeduction", "EmployeeDeduction")
                        .WithMany("PayrollDeductions")
                        .HasForeignKey("EmployeeDeductionId");

                    b.HasOne("WorkTrackBio.API.Data.Models.PayrollEntry", "Payroll")
                        .WithMany("PayrollDeductions")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDeduction");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollEntry", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("PayrollEntries")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.PayrollRun", "PayrollRun")
                        .WithMany("PayrollEntries")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInfo");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollRun", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.AppUser", "ApprovedBy")
                        .WithMany("ApprovedPayrollRuns")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkTrackBio.API.Data.Models.AppUser", "CreatedBy")
                        .WithMany("CreatedPayrollRuns")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Project", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId");

                    b.HasOne("WorkTrackBio.API.Data.Models.State", "State")
                        .WithMany("Projects")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ProjectMaintenance", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "MadeBy")
                        .WithMany()
                        .HasForeignKey("MadeById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.Project", "Project")
                        .WithMany("ProjectMaintenances")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.State", "State")
                        .WithMany("ProjectMaintenances")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MadeBy");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ProjectWarranty", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.Project", "Project")
                        .WithMany("ProjectWarranties")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "MadeBy")
                        .WithMany()
                        .HasForeignKey("MadeById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.State", "State")
                        .WithMany("ProjectWarranties")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MadeBy");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.SystemAuditLog", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.AppUser", "AppUser")
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.TravelExpense", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany()
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.Project", "Project")
                        .WithMany("TravelExpenses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkTrackBio.API.Data.Models.State", "State")
                        .WithMany("TravelExpenses")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("EmployeeInfo");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.UserSession", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.AppUser", "AppUser")
                        .WithMany("UserSessions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.VacationRequest", b =>
                {
                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkTrackBio.API.Data.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("VacationRequests")
                        .HasForeignKey("EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.AppUser", b =>
                {
                    b.Navigation("ApprovedPayrollRuns");

                    b.Navigation("CreatedPayrollRuns");

                    b.Navigation("SystemAuditLogs");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.ChristmasBonus", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Department", b =>
                {
                    b.Navigation("EmployeeInfos");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.DocumentType", b =>
                {
                    b.Navigation("EmployeeInfos");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeDeduction", b =>
                {
                    b.Navigation("PayrollDeductions");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.EmployeeInfo", b =>
                {
                    b.Navigation("AbsenceRecords");

                    b.Navigation("AppUser");

                    b.Navigation("Assistances");

                    b.Navigation("ChristmasBonuses");

                    b.Navigation("Disabilities");

                    b.Navigation("EmployeeDeductions");

                    b.Navigation("EmployeeDocuments");

                    b.Navigation("Liquidations");

                    b.Navigation("PayrollEntries");

                    b.Navigation("VacationRequests");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollEntry", b =>
                {
                    b.Navigation("PayrollDeductions");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.PayrollRun", b =>
                {
                    b.Navigation("PayrollEntries");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Project", b =>
                {
                    b.Navigation("Assistances");

                    b.Navigation("ProjectMaintenances");

                    b.Navigation("ProjectWarranties");

                    b.Navigation("TravelExpenses");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.Role", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("WorkTrackBio.API.Data.Models.State", b =>
                {
                    b.Navigation("EmployeeInfos");

                    b.Navigation("ProjectMaintenances");

                    b.Navigation("ProjectWarranties");

                    b.Navigation("Projects");

                    b.Navigation("TravelExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
