// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WTB.API.Data.Context;

#nullable disable

namespace WTB.API.Migrations
{
    [DbContext(typeof(WTBDbContext))]
    partial class WTBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WTB.API.Models.Entities.Assistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDateOnly")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("CAST([CheckIn] AS DATE)");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RegisterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInDateOnly")
                        .HasDatabaseName("IX_Assistance_CheckInDate");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Assistance_ProjectId");

                    b.HasIndex("EmployeeId", "ProjectId", "CheckIn")
                        .HasDatabaseName("IX_Assistance_EmployeeProjectCheckIn");

                    b.ToTable("Assistance");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.AuditRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("AssistanceId")
                        .HasColumnType("int");

                    b.Property<string>("DetailChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActionDate")
                        .HasDatabaseName("IX_AuditRegister_ActionDate");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("IX_AuditRegister_AdminId");

                    b.HasIndex("AssistanceId")
                        .HasDatabaseName("IX_AuditRegister_AssistanceId");

                    b.ToTable("AuditRegister");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentName")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentType_DocumentName");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.EmployeeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CostPerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DocumentExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_EmployeeInfo_DocumentNumber");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("IX_EmployeeInfo_DocumentTypeId");

                    b.HasIndex("StateId")
                        .HasDatabaseName("IX_EmployeeInfo_StateId");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_EmployeeInfo_FullName");

                    b.ToTable("EmployeeInfo");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.FingerPrint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TemplateFingerPrint")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_FingerPrint_EmployeeId");

                    b.ToTable("FingerPrint");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.InternUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_InternUsers_Email");

                    b.HasIndex("RolId")
                        .HasDatabaseName("IX_InternUsers_RolId");

                    b.HasIndex("StateId");

                    b.ToTable("InternUsers");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.ProjectMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProject")
                        .HasColumnType("int");

                    b.Property<int>("MadeById")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaintenanceCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("MaintenanceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MaintenanceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProject")
                        .HasDatabaseName("IX_ProjectMaintenance_IdProject");

                    b.HasIndex("MadeById")
                        .HasDatabaseName("IX_ProjectMaintenance_MadeById");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectMaintenance");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.ProjectWarranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProject")
                        .HasColumnType("int");

                    b.Property<int>("MadeById")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WarrantyCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("WarrantyDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WarrantyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProject")
                        .HasDatabaseName("IX_ProjectWarranty_IdProject");

                    b.HasIndex("MadeById")
                        .HasDatabaseName("IX_ProjectWarranty_MadeById");

                    b.HasIndex("StateId");

                    b.ToTable("ProjectWarranty");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectName")
                        .IsUnique()
                        .HasDatabaseName("IX_Projects_ProjectName");

                    b.HasIndex("StateId")
                        .HasDatabaseName("IX_Projects_StateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.ProjectsAssigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ProjectsAssigns_ProjectId");

                    b.HasIndex("EmployeeId", "ProjectId", "AssignDate")
                        .HasDatabaseName("IX_ProjectsAssigns_EmployeeProjectAssign");

                    b.ToTable("ProjectsAssigns");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_RoleName");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StateName", "StateType")
                        .IsUnique()
                        .HasDatabaseName("IX_States_StateName");

                    b.ToTable("States");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Assistance", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.EmployeeInfo", "Employee")
                        .WithMany("Assistances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeId_EmployeeInfo");

                    b.HasOne("WTB.API.Models.Entities.Projects", "Project")
                        .WithMany("Assistances")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectId_Projects");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.AuditRegister", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.InternUsers", "Admin")
                        .WithMany("AuditRegisters")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AuditRegister_InterUser");

                    b.HasOne("WTB.API.Models.Entities.Assistance", "Assistance")
                        .WithMany("AuditRegisters")
                        .HasForeignKey("AssistanceId")
                        .HasConstraintName("FK_AssitanceId_Assistance");

                    b.Navigation("Admin");

                    b.Navigation("Assistance");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Device", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.Projects", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.EmployeeInfo", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.DocumentType", "DocumentType")
                        .WithMany("EmployeeInfo")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeDocumentType_DocumentTypeId");

                    b.HasOne("WTB.API.Models.Entities.States", "State")
                        .WithMany("EmployeeInfo")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_StateId");

                    b.Navigation("DocumentType");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.FingerPrint", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.EmployeeInfo", "Employee")
                        .WithMany("FingerPrints")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FingerPrint_EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.InternUsers", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.Roles", "Role")
                        .WithMany("InternUsers")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InternUsers_RolId");

                    b.HasOne("WTB.API.Models.Entities.States", "State")
                        .WithMany("InternUsers")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InternUsers_StateId");

                    b.Navigation("Role");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.ProjectMaintenance", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.Projects", "Project")
                        .WithMany("ProjectMaintenances")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectMaintenance_ProjectId");

                    b.HasOne("WTB.API.Models.Entities.EmployeeInfo", "MadeBy")
                        .WithMany("ProjectMaintenancesMadeBy")
                        .HasForeignKey("MadeById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_MadeById");

                    b.HasOne("WTB.API.Models.Entities.States", "State")
                        .WithMany("ProjectMaintenances")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectMaintenance_StateId");

                    b.Navigation("MadeBy");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.ProjectWarranty", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.Projects", "Project")
                        .WithMany("ProjectWarranties")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectWarranty_IdProject");

                    b.HasOne("WTB.API.Models.Entities.EmployeeInfo", "MadeBy")
                        .WithMany("ProjectWarrantiesMadeBy")
                        .HasForeignKey("MadeById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectWarranty_MadeById");

                    b.HasOne("WTB.API.Models.Entities.States", "State")
                        .WithMany("ProjectWarranties")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectWarranty_StateId");

                    b.Navigation("MadeBy");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Projects", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.States", "State")
                        .WithMany("Projects")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Projects_StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.ProjectsAssigns", b =>
                {
                    b.HasOne("WTB.API.Models.Entities.EmployeeInfo", "Employee")
                        .WithMany("ProjectsAssigns")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectsAssigns_EmployeeId");

                    b.HasOne("WTB.API.Models.Entities.Projects", "Project")
                        .WithMany("ProjectsAssigns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectAssigns_ProjectId");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Assistance", b =>
                {
                    b.Navigation("AuditRegisters");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.DocumentType", b =>
                {
                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.EmployeeInfo", b =>
                {
                    b.Navigation("Assistances");

                    b.Navigation("FingerPrints");

                    b.Navigation("ProjectMaintenancesMadeBy");

                    b.Navigation("ProjectWarrantiesMadeBy");

                    b.Navigation("ProjectsAssigns");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.InternUsers", b =>
                {
                    b.Navigation("AuditRegisters");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Projects", b =>
                {
                    b.Navigation("Assistances");

                    b.Navigation("ProjectMaintenances");

                    b.Navigation("ProjectWarranties");

                    b.Navigation("ProjectsAssigns");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.Roles", b =>
                {
                    b.Navigation("InternUsers");
                });

            modelBuilder.Entity("WTB.API.Models.Entities.States", b =>
                {
                    b.Navigation("EmployeeInfo");

                    b.Navigation("InternUsers");

                    b.Navigation("ProjectMaintenances");

                    b.Navigation("ProjectWarranties");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
