IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'WTB_DB')
BEGIN
	CREATE DATABASE WTB_DB;
END
GO

USE WTB_DB;
GO

--CREATE STATES TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'States')
BEGIN
	CREATE TABLE States(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StateName NVARCHAR(50) NOT NULL UNIQUE,
	StateType NVARCHAR(50) NOT NULL,
	Description NVARCHAR(50) NULL
	);
END
GO

-- CREATE ROLES TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='Roles')
BEGIN
	CREATE TABLE Roles (
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	RolName NVARCHAR(50) NOT NULL UNIQUE,
	Description NVARCHAR(255) NULL
	);
END
GO

-- CREATE INTERNUSERS TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='InternUsers')
BEGIN
	CREATE TABLE InternUsers (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	PasswordSalt NVARCHAR(100) NOT NULL,
	RolId INT NOT NULL,
	CONSTRAINT FK_InternUsers_RolId FOREIGN KEY (RolId) REFERENCES Roles(Id),
	CreationDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	StateId INT NOT NULL,
	CONSTRAINT FK_InternUsers_StateId FOREIGN KEY (StateId) REFERENCES States(Id),
	LastLogin DATETIME2 NULL
	);
END
GO

--CREATE PROJECTS TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='Projects')
BEGIN
	CREATE TABLE Projects (
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	ProjectName NVARCHAR(150) NOT NULL UNIQUE,
	StartDate DATE NULL,
	EndDate DATE NULL,
	StateId INT NOT NULL,
	CONSTRAINT FK_Projects_StateId FOREIGN KEY (StateId) REFERENCES States(Id)
	);
END
GO

--CREATE DOCUMENT TYPE TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='DocumentType')
BEGIN
	CREATE TABLE DocumentType (
	Id INT IDENTITY (1,1) PRIMARY KEY,
	DocumentName NVARCHAR(50) NOT NULL,
	Description NVARCHAR(255) NULL
	);
END
GO

--CREATE EMPLOYEE INFO
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='EmployeeInfo')
BEGIN
	CREATE TABLE EmployeeInfo(
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	DocumentNumber NVARCHAR(50) NOT NULL UNIQUE,
	DocumentTypeId INT NOT NULL,
	CONSTRAINT FK_EmployeeDocumentType_DocumentTypeId FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),
	DocumentExpire DATE NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	PhoneNumber NVARCHAR(20) NULL,
	Birthday DATE NOT NULL,
	RegisterDate DATETIME2 DEFAULT GETDATE() NOT NULL,
	StateId INT NOT NULL,
	CONSTRAINT FK_Employee_StateId FOREIGN KEY (StateId) REFERENCES States(Id),
	Address NVARCHAR(255) NULL,
	IBAN NVARCHAR(50) NULL
	);
END
GO

--CREATE ASSISTANCE TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='Assistance')
BEGIN
	CREATE TABLE Assistance (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	EmployeeId INT NOT NULL,
	CONSTRAINT FK_EmployeeId_EmployeeInfo FOREIGN KEY (EmployeeId) REFERENCES EmployeeInfo(Id),
	ProjectId INT NOT NULL,
	CONSTRAINT FK_ProjectId_Projects FOREIGN KEY (ProjectId) REFERENCES Projects(Id),
	CheckIn DATETIME2 NOT NULL,
	CheckOut DATETIME2 NULL,
	TotalHours DECIMAL(5,2) NULL,
	RegisterType NVARCHAR(50) NOT NULL
	);
END
GO

--CREATE PROJECTS ASSIGNS
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ProjectsAssings')
BEGIN
	CREATE TABLE ProjectsAssigns (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	EmployeeId INT NOT NULL,
	CONSTRAINT FK_ProjectsAssigns_EmployeeId FOREIGN KEY (EmployeeId) REFERENCES EmployeeInfo(Id),
	ProjectId INT NOT NULL,
	CONSTRAINT FK_ProjectAssigns_ProjectId FOREIGN KEY (ProjectId) REFERENCES Projects(Id),
	AssignDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	EndDate DATETIME2 NULL
	);
END
GO

--CREATE TABLE AUDIT REGISTER
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='AuditRegister')
BEGIN
	CREATE TABLE AuditRegister (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	AssistanceId INT NOT NULL,
	CONSTRAINT FK_AssitanceId_Assistance FOREIGN KEY (AssistanceId) REFERENCES Assistance(Id),
	ActionType NVARCHAR(50) NOT NULL,
	DetailChange NVARCHAR(MAX) NOT NULL,
	ActionDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	AdminId INT NOT NULL,
	CONSTRAINT FK_AuditRegister_InterUser FOREIGN KEY (AdminId) REFERENCES InternUsers(Id)
	);

--CREATE FINGERPRINT TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FingerPrint')
BEGIN
	CREATE TABLE FingerPrint(
	Id INT PRIMARY KEY IDENTITY (1,1),
	EmployeeId INT NOT NULL,
	CONSTRAINT FK_FingerPrint_EmployeeId FOREIGN KEY (EmployeeId) REFERENCES EmployeeInfo(Id),
	TemplateFingerPrint VARBINARY(MAX) NOT NULL,
	IssueDate DATETIME2 NOT NULL DEFAULT GETDATE()
	);
END
GO

--CREATE MAINTENANCE TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='ProjectMaintenance')
BEGIN
	CREATE TABLE ProjectMaintenance (
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IdProject INT NOT NULL,
	CONSTRAINT FK_ProjectMaintenance_ProjectId FOREIGN KEY (IdProject) REFERENCES Projects(Id),
	MaintenanceDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	MaintenanceDescription NVARCHAR(MAX) NOT NULL,
	MadeById INT NOT NULL,
	CONSTRAINT FK_Maintenance_MadeById FOREIGN KEY (MadeById) REFERENCES EmployeeInfo(Id),
	MaintenanceCost DECIMAL(10,2) NULL,
	AdditionalInfo NVARCHAR(255) NULL,
	StateId INT NOT NULL,
	CONSTRAINT FK_ProjectMaintenance_StateId FOREIGN KEY (StateId) REFERENCES States(Id)
	);
END
GO

--CREATE WARRANTY TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='ProjectWarranty')
BEGIN
	CREATE TABLE ProjectWarranty (
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IdProject INT NOT NULL,
	CONSTRAINT FK_ProjectWarranty_IdProject FOREIGN KEY (IdProject) REFERENCES Projects(Id),
	WarrantyDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	WarrantyDescription NVARCHAR(MAX) NOT NULL,
	MadeById INT NOT NULL,
	CONSTRAINT FK_ProjectWarranty_MadeById FOREIGN KEY (MadeById) REFERENCES EmployeeInfo(Id),
	WarrantyCost DECIMAL(10,2) NULL,
	StateId INT NOT NULL,
	CONSTRAINT FK_ProjectWarranty_StateId FOREIGN KEY (StateId) REFERENCES States(Id)
	);
END
GO