IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'WTB_DB')
BEGIN
	CREATE DATABASE WTB_DB;
END
GO

USE WTB_DB;
GO

-- CREATE ROLES TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='Roles')
BEGIN
	CREATE TABLE Roles (
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	RolName NVARCHAR(50) NOT NULL UNIQUE,
	Description NVARCHAR(255) NULL
	);
END
GO

-- CREATE INTERNUSERS TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name ='InternUsers')
BEGIN
	CREATE TABLE InternUsers (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	PasswordSalt NVARCHAR(100) NOT NULL,
	RolId INT NOT NULL,
	CONSTRAINT FK_InternUsers_RolId FOREIGN KEY (RolId) REFERENCES Roles(Id),
	CreationDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	Active BIT NOT NULL DEFAULT 1,
	LastLogin DATETIME2 NULL
	);
END
GO